# Generated by Django 3.2.6 on 2021-08-04 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('number', models.BigIntegerField()),
                ('type', models.CharField(choices=[('D', 'doctor'), ('P', 'patient')], max_length=10)),
            ],
        ),
    ]
